
const DashboardConstants = {
    RECEIVE_RAW_WEATHER: 'RECEIVE_RAW_WEATHER',
    RECEIVE_RAW_WEATHERALERTS: 'RECEIVE_RAW_WEATHERALERTS',
    RECEIVE_RAW_POLLEN: 'RECEIVE_RAW_POLLEN',
    RECEIVE_RAW_CALENDAR_EVENTS: 'RECEIVE_RAW_CALENDAR_EVENTS',
    RECEIVE_RAW_NEWS_EVENTS: 'RECEIVE_RAW_NEWS_EVENTS',
    RECEIVE_QUAKE_INFO: 'RECEIVE_QUAKE_INFO',
    RECEIVE_SYSTEM_ENDPOINT: 'RECEIVE_SYSTEM_ENDPOINT',
    RECEIVE_SYSTEM_WIFIAPS: 'RECEIVE_SYSTEM_WIFIAPS',
    RECEIVE_SYSTEM_VERSIONINFO: 'RECEIVE_SYSTEM_VERSIONINFO',
    RECEIVE_SYSTEM_CONFIG: 'RECEIVE_SYSTEM_CONFIG',
    RECEIVE_SYSTEM_CONFIG_ERROR: 'RECEIVE_SYSTEM_CONFIG_ERROR'
};

export default DashboardConstants;